# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_client/ui/setting_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingDialog(object):
    def setupUi(self, SettingDialog):
        SettingDialog.setObjectName("SettingDialog")
        SettingDialog.setWindowModality(QtCore.Qt.NonModal)
        SettingDialog.resize(400, 298)
        SettingDialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(SettingDialog)
        self.buttonBox.setGeometry(QtCore.QRect(0, 260, 391, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(SettingDialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 381, 84))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.gridLayout.addWidget(self.comboBox_2, 1, 2, 1, 1)
        self.bg_box = QtWidgets.QComboBox(self.widget)
        self.bg_box.setObjectName("bg_box")
        self.bg_box.addItem("")
        self.bg_box.addItem("")
        self.bg_box.addItem("")
        self.bg_box.addItem("")
        self.gridLayout.addWidget(self.bg_box, 0, 2, 1, 1)
        self.bg_label = QtWidgets.QLabel(self.widget)
        self.bg_label.setObjectName("bg_label")
        self.gridLayout.addWidget(self.bg_label, 0, 0, 1, 2)

        self.retranslateUi(SettingDialog)
        self.buttonBox.accepted.connect(SettingDialog.accept)
        self.buttonBox.rejected.connect(SettingDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingDialog)

    def retranslateUi(self, SettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingDialog.setWindowTitle(_translate("SettingDialog", "Settings"))
        self.label_2.setText(_translate("SettingDialog", "Language"))
        self.bg_box.setItemText(0, _translate("SettingDialog", "white"))
        self.bg_box.setItemText(1, _translate("SettingDialog", "black"))
        self.bg_box.setItemText(2, _translate("SettingDialog", "yellow"))
        self.bg_box.setItemText(3, _translate("SettingDialog", "green"))
        self.bg_label.setText(_translate("SettingDialog", "Background Color"))
